# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: act_samples.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("act_samples.proto", :syntax => :proto2) do
    add_message "polar_data.PbSportInfo" do
      required :factor, :float, 1
      required :time_stamp, :message, 2, "PbLocalDateTime"
      optional :sport_profile_id, :uint64, 3
    end
    add_message "polar_data.PbActivityInfo" do
      required :value, :enum, 1, "polar_data.PbActivityInfo.ActivityClass"
      required :time_stamp, :message, 2, "PbLocalDateTime"
      optional :factor, :float, 3
    end
    add_enum "polar_data.PbActivityInfo.ActivityClass" do
      value :SLEEP, 1
      value :SEDENTARY, 2
      value :LIGHT, 3
      value :CONTINUOUS_MODERATE, 4
      value :INTERMITTENT_MODERATE, 5
      value :CONTINUOUS_VIGOROUS, 6
      value :INTERMITTENT_VIGOROUS, 7
      value :NON_WEAR, 8
    end
    add_message "polar_data.PbInActivityTriggerInfo" do
      required :time_stamp, :message, 1, "PbLocalDateTime"
    end
    add_message "polar_data.PbInActivityNonWearTriggerInfo" do
      required :start_time_stamp, :message, 1, "PbLocalDateTime"
      required :end_time_stamp, :message, 2, "PbLocalDateTime"
    end
    add_message "polar_data.PbActivitySamples" do
      required :start_time, :message, 1, "PbLocalDateTime"
      required :met_recording_interval, :message, 2, "PbDuration"
      required :steps_recording_interval, :message, 3, "PbDuration"
      repeated :met_samples, :float, 4
      repeated :steps_samples, :uint32, 5
      repeated :sport_info, :message, 6, "polar_data.PbSportInfo"
      repeated :activity_info, :message, 7, "polar_data.PbActivityInfo"
      repeated :inactivity_trigger, :message, 8, "polar_data.PbInActivityTriggerInfo"
      repeated :inactivity_non_wear_trigger, :message, 9, "polar_data.PbInActivityNonWearTriggerInfo"
    end
  end
end

module PolarData
  PbSportInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportInfo").msgclass
  PbActivityInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivityInfo").msgclass
  PbActivityInfo::ActivityClass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivityInfo.ActivityClass").enummodule
  PbInActivityTriggerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbInActivityTriggerInfo").msgclass
  PbInActivityNonWearTriggerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbInActivityNonWearTriggerInfo").msgclass
  PbActivitySamples = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivitySamples").msgclass
end
