# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bluetooth_device.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("bluetooth_device.proto", :syntax => :proto2) do
    add_message "polar_data.PbBleUuid" do
      required :uuid, :bytes, 1
    end
    add_message "polar_data.PbBleCharacteristic" do
      required :handle, :uint32, 1
      required :type, :message, 2, "polar_data.PbBleUuid"
    end
    add_message "polar_data.PbBleService" do
      required :serviceUuid, :message, 1, "polar_data.PbBleUuid"
      repeated :characteristics, :message, 2, "polar_data.PbBleCharacteristic"
    end
    add_message "polar_data.PbBleUser" do
      required :user_index, :uint32, 1
      required :device_user_index, :uint32, 2
      optional :consent, :uint32, 3
    end
    add_message "polar_data.PbBleDevice" do
      required :paired, :message, 1, "PbSystemDateTime"
      required :last_modified, :message, 2, "PbSystemDateTime"
      required :manufacturer, :enum, 3, "polar_data.PbDeviceManufacturerType"
      optional :deleted_time_stamp, :message, 5, "PbSystemDateTime"
      optional :mac, :message, 6, "PbBleMac"
      optional :device_id, :string, 7
      optional :name, :string, 8
      optional :battery_level, :uint32, 9
      optional :manufacturer_name, :string, 10
      optional :model_name, :string, 11
      optional :peer_ltk, :bytes, 12
      optional :peer_irk, :bytes, 13
      optional :peer_csrk, :bytes, 14
      repeated :available_features, :enum, 15, "PbFeatureType"
      repeated :services, :message, 16, "polar_data.PbBleService"
      optional :peer_rand, :bytes, 17
      optional :peer_ediv, :uint32, 18
      optional :encr_key_size, :uint32, 19
      optional :distributed_keys, :uint32, 20
      optional :authenticated, :bool, 21
      optional :sensor_location, :enum, 22, "polar_data.PbBleDevice.PbSensorLocation"
      optional :software_version, :string, 23
      optional :secondary_software_version, :string, 24
      optional :serial_number, :string, 25
      optional :local_ltk, :bytes, 26
      optional :local_rand, :bytes, 27
      optional :local_ediv, :uint32, 28
      repeated :user_data, :message, 29, "polar_data.PbBleUser"
    end
    add_enum "polar_data.PbBleDevice.PbBleKeyType" do
      value :BLE_PEER_ENCRYPTION_KEY, 1
      value :BLE_PEER_IDENTIFICATION_KEY, 2
      value :BLE_PEER_SIGNING_KEY, 4
      value :BLE_LOCAL_ENCRYPTION_KEY, 8
      value :BLE_LOCAL_IDENTIFICATION_KEY, 16
      value :BLE_LOCAL_SIGNING_KEY, 32
    end
    add_enum "polar_data.PbBleDevice.PbSensorLocation" do
      value :SENSOR_LOCATION_OTHER, 0
      value :SENSOR_LOCATION_TOP_OF_SHOE, 1
      value :SENSOR_LOCATION_IN_SHOE, 2
      value :SENSOR_LOCATION_HIP, 3
      value :SENSOR_LOCATION_FRONT_WHEEL, 4
      value :SENSOR_LOCATION_LEFT_CRANK, 5
      value :SENSOR_LOCATION_RIGHT_CRANK, 6
      value :SENSOR_LOCATION_LEFT_PEDAL, 7
      value :SENSOR_LOCATION_RIGHT_PEDAL, 8
      value :SENSOR_LOCATION_FRONT_HUB, 9
      value :SENSOR_LOCATION_REAR_DROPOUT, 10
      value :SENSOR_LOCATION_CHAINSTAY, 11
      value :SENSOR_LOCATION_REAR_WHEEL, 12
      value :SENSOR_LOCATION_REAR_HUB, 13
      value :SENSOR_LOCATION_CHEST, 14
    end
    add_enum "polar_data.PbDeviceManufacturerType" do
      value :MANUFACTURER_POLAR, 1
      value :MANUFACTURER_OTHER, 2
    end
  end
end

module PolarData
  PbBleUuid = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleUuid").msgclass
  PbBleCharacteristic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleCharacteristic").msgclass
  PbBleService = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleService").msgclass
  PbBleUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleUser").msgclass
  PbBleDevice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleDevice").msgclass
  PbBleDevice::PbBleKeyType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleDevice.PbBleKeyType").enummodule
  PbBleDevice::PbSensorLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbBleDevice.PbSensorLocation").enummodule
  PbDeviceManufacturerType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDeviceManufacturerType").enummodule
end
