# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dailysummary.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dailysummary.proto", :syntax => :proto2) do
    add_message "polar_data.PbActivityGoalSummary" do
      required :activity_goal, :float, 1
      required :achieved_activity, :float, 2
      optional :time_to_go_up, :message, 3, "PbDuration"
      optional :time_to_go_walk, :message, 4, "PbDuration"
      optional :time_to_go_jog, :message, 5, "PbDuration"
    end
    add_message "polar_data.PbActivityClassTimes" do
      required :time_non_wear, :message, 1, "PbDuration"
      required :time_sleep, :message, 2, "PbDuration"
      required :time_sedentary, :message, 3, "PbDuration"
      required :time_light_activity, :message, 4, "PbDuration"
      required :time_continuous_moderate, :message, 5, "PbDuration"
      required :time_intermittent_moderate, :message, 6, "PbDuration"
      required :time_continuous_vigorous, :message, 7, "PbDuration"
      required :time_intermittent_vigorous, :message, 8, "PbDuration"
    end
    add_message "polar_data.PbDailySummary" do
      required :date, :message, 1, "PbDate"
      optional :steps, :uint32, 2
      optional :activity_calories, :uint32, 3
      optional :training_calories, :uint32, 4
      optional :bmr_calories, :uint32, 5
      optional :activity_goal_summary, :message, 6, "polar_data.PbActivityGoalSummary"
      optional :activity_class_times, :message, 7, "polar_data.PbActivityClassTimes"
      optional :activity_distance, :float, 8
    end
  end
end

module PolarData
  PbActivityGoalSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivityGoalSummary").msgclass
  PbActivityClassTimes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivityClassTimes").msgclass
  PbDailySummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDailySummary").msgclass
end
