# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daily_training_load.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("daily_training_load.proto", :syntax => :proto2) do
    add_message "polar_data.PbDailyTrainingLoadSummary" do
      required :trimp, :float, 1
      required :acute_load, :float, 2
      required :chronic_load, :float, 3
      required :unknown, :uint32, 4
    end
    add_message "polar_data.PbDailyTrainingLoadUnknown2" do
      required :unknown2_1, :float, 1
      required :unknown2_2, :float, 2
    end
    add_message "polar_data.PbDailyTrainingLoadUnknown4" do
      required :unknown4_1, :uint64, 1
      required :unknown4_2, :message, 2, "polar_data.PbDailyTrainingLoadUnknown2"
      required :unknown4_3, :message, 3, "polar_data.PbDailyTrainingLoadUnknown2"
    end
    add_message "polar_data.PbDailyTrainingLoad" do
      required :summary, :message, 1, "polar_data.PbDailyTrainingLoadSummary"
      required :avg_90d_load, :float, 2
      required :unknown4, :message, 4, "polar_data.PbDailyTrainingLoadUnknown4"
      required :unknown5, :float, 5
      required :date, :message, 100, "PbLocalDateTime"
    end
  end
end

module PolarData
  PbDailyTrainingLoadSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDailyTrainingLoadSummary").msgclass
  PbDailyTrainingLoadUnknown2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDailyTrainingLoadUnknown2").msgclass
  PbDailyTrainingLoadUnknown4 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDailyTrainingLoadUnknown4").msgclass
  PbDailyTrainingLoad = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDailyTrainingLoad").msgclass
end
