# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("device.proto", :syntax => :proto2) do
    add_message "polar_data.PbVersion" do
      required :major, :uint32, 1
      required :minor, :uint32, 2
      required :patch, :uint32, 3
      optional :specifier, :string, 4
    end
    add_message "polar_data.PbDeviceInfo" do
      optional :bootloader_version, :message, 1, "polar_data.PbVersion"
      optional :platform_version, :message, 2, "polar_data.PbVersion"
      optional :device_version, :message, 3, "polar_data.PbVersion"
      optional :svn_rev, :uint32, 4
      optional :electrical_serial_number, :string, 5
      optional :deviceID, :string, 6
      optional :model_name, :string, 7
      optional :hardware_code, :string, 8
      optional :product_color, :string, 9
      optional :product_design, :string, 10
      optional :system_id, :string, 11
    end
  end
end

module PolarData
  PbVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbVersion").msgclass
  PbDeviceInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDeviceInfo").msgclass
end
