# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_phases_reps.proto

require 'google/protobuf'

require 'types_pb'
require 'exercise_stats_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_phases_reps.proto", :syntax => :proto2) do
    add_message "polar_data.PbPhaseHeartRateStatistics" do
      optional :average, :uint32, 1
      optional :maximum, :uint32, 2
    end
    add_message "polar_data.PbPhaseStrideLengthStatistics" do
      optional :average, :uint32, 1
    end
    add_message "polar_data.PbPhaseRepetition" do
      required :index, :uint32, 1
      required :split_time, :message, 2, "PbDuration"
      required :duration, :message, 3, "PbDuration"
      optional :phase_finished, :bool, 4
      optional :split_distance, :float, 5
      optional :distance, :float, 6
      optional :in_target_zone, :message, 7, "PbDuration"
      optional :heart_rate, :message, 8, "polar_data.PbPhaseHeartRateStatistics"
      optional :speed, :message, 9, "polar_data.PbSpeedStatistics"
      optional :cadence, :message, 10, "polar_data.PbCadenceStatistics"
      optional :power, :message, 11, "polar_data.PbPowerStatistics"
      optional :left_right_balance, :message, 12, "polar_data.PbLRBalanceStatistics"
      optional :stride_length, :message, 13, "polar_data.PbPhaseStrideLengthStatistics"
      optional :stroke_count, :uint32, 14
      optional :average_swolf, :float, 15
      optional :strokes_per_min, :uint32, 16
      optional :ascent, :float, 17
      optional :descent, :float, 18
    end
    add_message "polar_data.PbPhaseRepetitions" do
      repeated :phase, :message, 1, "polar_data.PbPhaseRepetition"
    end
  end
end

module PolarData
  PbPhaseHeartRateStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPhaseHeartRateStatistics").msgclass
  PbPhaseStrideLengthStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPhaseStrideLengthStatistics").msgclass
  PbPhaseRepetition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPhaseRepetition").msgclass
  PbPhaseRepetitions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPhaseRepetitions").msgclass
end
