# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_sensors.proto

require 'google/protobuf'

require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_sensors.proto", :syntax => :proto2) do
    add_message "polar_data.PbExerciseSensor" do
      required :mac, :message, 1, "PbBleMac"
      optional :device_id, :message, 2, "PbDeviceId"
      optional :device_name, :message, 3, "PbBleDeviceName"
    end
    add_message "polar_data.PbExerciseSensors" do
      repeated :sensors, :message, 1, "polar_data.PbExerciseSensor"
    end
  end
end

module PolarData
  PbExerciseSensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseSensor").msgclass
  PbExerciseSensors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseSensors").msgclass
end
