# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_route.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_route.proto", :syntax => :proto2) do
    add_message "polar_data.PbExerciseRouteSamples" do
      repeated :duration, :uint32, 1
      repeated :latitude, :double, 2
      repeated :longitude, :double, 3
      repeated :gps_altitude, :sint32, 4
      repeated :satellite_amount, :uint32, 5
      repeated :OBSOLETE_fix, :bool, 6
      repeated :OBSOLETE_gps_offline, :message, 7, "PbSensorOffline"
      repeated :OBSOLETE_gps_date_time, :message, 8, "PbSystemDateTime"
      optional :first_location_time, :message, 9, "PbSystemDateTime"
    end
  end
end

module PolarData
  PbExerciseRouteSamples = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseRouteSamples").msgclass
end
