# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_targetinfo.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
require 'training_session_target_pb'
require 'exercise_phases_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_targetinfo.proto", :syntax => :proto2) do
    add_message "polar_data.PbSteadyRacePaceResult" do
      required :completed_time, :message, 1, "PbDuration"
      optional :average_heartrate, :uint32, 2
      optional :average_speed, :float, 3
    end
    add_message "polar_data.PbExerciseTargetInfo" do
      required :target_type, :enum, 1, "PbExerciseTargetType"
      required :index, :uint32, 2
      optional :name, :message, 3, "PbOneLineText"
      optional :target_reached, :bool, 4
      optional :end_time, :message, 5, "PbDuration"
      optional :sport_id, :message, 6, "PbSportIdentifier"
      optional :volume_target, :message, 7, "PbVolumeTarget"
      optional :phases, :message, 8, "polar_data.PbPhases"
      optional :route, :message, 9, "PbRouteId"
      optional :steady_race_pace, :message, 10, "polar_data.PbSteadyRacePace"
      optional :steady_race_pace_result, :message, 11, "polar_data.PbSteadyRacePaceResult"
    end
  end
end

module PolarData
  PbSteadyRacePaceResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSteadyRacePaceResult").msgclass
  PbExerciseTargetInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseTargetInfo").msgclass
end
