# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_samples.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
require 'exercise_rr_samples_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_samples.proto", :syntax => :proto2) do
    add_message "polar_data.PbPowerMeasurements" do
      required :current_power, :int32, 1
      optional :cumulative_crank_revolutions, :uint32, 2
      optional :cumulative_timestamp, :uint32, 3
      optional :force_magnitude_min, :sint32, 4
      optional :force_magnitude_max, :int32, 5
      optional :force_magnitude_min_angle, :uint32, 6
      optional :force_magnitude_max_angle, :uint32, 7
      optional :bottom_dead_spot_angle, :uint32, 8
      optional :top_dead_spot_angle, :uint32, 9
    end
    add_message "polar_data.PbCalibrationValue" do
      required :start_index, :uint32, 1
      required :value, :float, 2
      required :operation, :enum, 3, "PbOperationType"
      optional :cause, :enum, 4, "PbMovingType"
    end
    add_message "polar_data.PbExerciseSamples" do
      required :recording_interval, :message, 1, "PbDuration"
      repeated :heart_rate_samples, :uint32, 2
      repeated :heart_rate_offline, :message, 3, "PbSensorOffline"
      repeated :cadence_samples, :uint32, 4
      repeated :cadence_offline, :message, 5, "PbSensorOffline"
      repeated :altitude_samples, :float, 6
      repeated :altitude_offline, :message, 18, "PbSensorOffline"
      repeated :altitude_calibration, :message, 7, "polar_data.PbCalibrationValue"
      repeated :temperature_samples, :float, 8
      repeated :temperature_offline, :message, 19, "PbSensorOffline"
      repeated :speed_samples, :float, 9
      repeated :speed_offline, :message, 10, "PbSensorOffline"
      repeated :distance_samples, :float, 11
      repeated :distance_offline, :message, 12, "PbSensorOffline"
      repeated :stride_length_samples, :uint32, 13
      repeated :stride_length_offline, :message, 14, "PbSensorOffline"
      repeated :stride_calibration, :message, 15, "polar_data.PbCalibrationValue"
      repeated :forward_acceleration, :float, 16
      repeated :forward_acceleration_offline, :message, 20, "PbSensorOffline"
      repeated :moving_type_samples, :enum, 17, "PbMovingType"
      repeated :moving_type_offline, :message, 21, "PbSensorOffline"
      repeated :left_pedal_power_samples, :message, 22, "polar_data.PbPowerMeasurements"
      repeated :left_pedal_power_offline, :message, 23, "PbSensorOffline"
      repeated :right_pedal_power_samples, :message, 24, "polar_data.PbPowerMeasurements"
      repeated :right_pedal_power_offline, :message, 25, "PbSensorOffline"
      repeated :left_power_calibration, :message, 26, "polar_data.PbCalibrationValue"
      repeated :right_power_calibration, :message, 27, "polar_data.PbCalibrationValue"
      optional :rr_samples, :message, 28, "polar_data.PbExerciseRRIntervals"
      repeated :pause_times, :message, 30, "PbPauseTime"
    end
  end
end

module PolarData
  PbPowerMeasurements = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPowerMeasurements").msgclass
  PbCalibrationValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbCalibrationValue").msgclass
  PbExerciseSamples = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseSamples").msgclass
end
