# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_rr_samples.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_rr_samples.proto", :syntax => :proto2) do
    add_message "polar_data.PbRROffline" do
      required :start_time, :message, 1, "PbDuration"
      required :time_interval, :message, 2, "PbDuration"
    end
    add_message "polar_data.PbExerciseRRIntervals" do
      repeated :rr_intervals, :uint32, 1
      repeated :rr_sensor_offline, :message, 2, "polar_data.PbRROffline"
    end
  end
end

module PolarData
  PbRROffline = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbRROffline").msgclass
  PbExerciseRRIntervals = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseRRIntervals").msgclass
end
