#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'types.pb'; rescue LoadError; end

module PolarData
  # forward declarations
  class PbRROffline < ::ProtocolBuffers::Message; end
  class PbExerciseRRIntervals < ::ProtocolBuffers::Message; end

  class PbRROffline < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbRROffline"

    required ::PbDuration, :start_time, 1
    required ::PbDuration, :time_interval, 2
  end

  class PbExerciseRRIntervals < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbExerciseRRIntervals"

    repeated :uint32, :rr_intervals, 1, :packed => true 
    repeated ::PolarData::PbRROffline, :rr_sensor_offline, 2
  end

end
