# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_stats.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("exercise_stats.proto", :syntax => :proto2) do
    add_message "polar_data.PbSwimmingStyleStatistics" do
      required :distance, :float, 1
      required :stroke_count, :uint32, 2
      optional :swimming_time_total, :message, 3, "PbDuration"
      optional :average_heartrate, :uint32, 4
      optional :maximum_heartrate, :uint32, 5
      optional :average_swolf, :float, 6
      optional :pool_time_min, :message, 7, "PbDuration"
    end
    add_message "polar_data.PbSwimmingStatistics" do
      required :swimming_distance, :float, 1
      optional :freestyle_statistics, :message, 2, "polar_data.PbSwimmingStyleStatistics"
      optional :backstroke_statistics, :message, 3, "polar_data.PbSwimmingStyleStatistics"
      optional :breaststroke_statistics, :message, 4, "polar_data.PbSwimmingStyleStatistics"
      optional :butterfly_statistics, :message, 5, "polar_data.PbSwimmingStyleStatistics"
      optional :total_stroke_count, :uint32, 6
      optional :number_of_pools_swimmed, :uint32, 7
      optional :swimming_pool, :message, 8, "PbSwimmingPoolInfo"
    end
    add_message "polar_data.PbHeartRateStatistics" do
      optional :minimum, :uint32, 1
      optional :average, :uint32, 2
      optional :maximum, :uint32, 3
    end
    add_message "polar_data.PbSpeedStatistics" do
      optional :average, :float, 1
      optional :maximum, :float, 2
    end
    add_message "polar_data.PbCadenceStatistics" do
      optional :average, :uint32, 1
      optional :maximum, :uint32, 2
    end
    add_message "polar_data.PbAltitudeStatistics" do
      optional :minimum, :float, 1
      optional :average, :float, 2
      optional :maximum, :float, 3
    end
    add_message "polar_data.PbPowerStatistics" do
      optional :average, :int32, 1
      optional :maximum, :int32, 2
    end
    add_message "polar_data.PbCyclingEfficiencyStatistics" do
      optional :average, :uint32, 1
    end
    add_message "polar_data.PbPedalingEfficiencyStatistics" do
      optional :average, :uint32, 1
    end
    add_message "polar_data.PbLRBalanceStatistics" do
      optional :average, :float, 1
    end
    add_message "polar_data.PbTemperatureStatistics" do
      optional :minimum, :float, 1
      optional :average, :float, 2
      optional :maximum, :float, 3
    end
    add_message "polar_data.PbStrideLengthStatistics" do
      optional :average, :uint32, 1
      optional :maximum, :uint32, 2
    end
    add_message "polar_data.PbInclineStatistics" do
      optional :average, :float, 1
      optional :maximum, :float, 2
    end
    add_message "polar_data.PbDeclineStatistics" do
      optional :average, :float, 1
      optional :maximum, :float, 2
    end
    add_message "polar_data.PbActivityStatistics" do
      optional :average, :float, 1
    end
    add_message "polar_data.PbExerciseStatistics" do
      optional :heart_rate, :message, 1, "polar_data.PbHeartRateStatistics"
      optional :speed, :message, 2, "polar_data.PbSpeedStatistics"
      optional :cadence, :message, 3, "polar_data.PbCadenceStatistics"
      optional :altitude, :message, 4, "polar_data.PbAltitudeStatistics"
      optional :power, :message, 5, "polar_data.PbPowerStatistics"
      optional :left_right_balance, :message, 6, "polar_data.PbLRBalanceStatistics"
      optional :temperature, :message, 7, "polar_data.PbTemperatureStatistics"
      optional :activity, :message, 8, "polar_data.PbActivityStatistics"
      optional :stride_length, :message, 9, "polar_data.PbStrideLengthStatistics"
      optional :incline, :message, 10, "polar_data.PbInclineStatistics"
      optional :decline, :message, 11, "polar_data.PbDeclineStatistics"
      optional :swimming, :message, 12, "polar_data.PbSwimmingStatistics"
    end
  end
end

module PolarData
  PbSwimmingStyleStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSwimmingStyleStatistics").msgclass
  PbSwimmingStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSwimmingStatistics").msgclass
  PbHeartRateStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbHeartRateStatistics").msgclass
  PbSpeedStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSpeedStatistics").msgclass
  PbCadenceStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbCadenceStatistics").msgclass
  PbAltitudeStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAltitudeStatistics").msgclass
  PbPowerStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPowerStatistics").msgclass
  PbCyclingEfficiencyStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbCyclingEfficiencyStatistics").msgclass
  PbPedalingEfficiencyStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPedalingEfficiencyStatistics").msgclass
  PbLRBalanceStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbLRBalanceStatistics").msgclass
  PbTemperatureStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTemperatureStatistics").msgclass
  PbStrideLengthStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbStrideLengthStatistics").msgclass
  PbInclineStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbInclineStatistics").msgclass
  PbDeclineStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDeclineStatistics").msgclass
  PbActivityStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivityStatistics").msgclass
  PbExerciseStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseStatistics").msgclass
end
