# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fitnesstestresult.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("fitnesstestresult.proto", :syntax => :proto2) do
    add_message "polar_data.PbFitnessTestResult" do
      required :start_time, :message, 1, "PbLocalDateTime"
      required :fitness, :uint32, 2
      required :unknonw, :uint32, 3
      required :hr_avg, :uint32, 4
    end
  end
end

module PolarData
  PbFitnessTestResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbFitnessTestResult").msgclass
end
