# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpsalmanacinfo.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gpsalmanacinfo.proto", :syntax => :proto2) do
    add_message "polar_data.PbGPSAlmanacInfo" do
      required :end_time, :message, 1, "PbSystemDateTime"
    end
  end
end

module PolarData
  PbGPSAlmanacInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbGPSAlmanacInfo").msgclass
end
