# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jumptest.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("jumptest.proto", :syntax => :proto2) do
    add_message "polar_data.PbJump" do
      required :flight_time, :message, 1, "PbDuration"
      optional :contact_time, :message, 2, "PbDuration"
    end
    add_message "polar_data.PbJumpTest" do
      required :test_type, :enum, 1, "polar_data.PbJumpTest.PbJumpTestType"
      required :start_time, :message, 2, "PbLocalDateTime"
      repeated :jump, :message, 3, "polar_data.PbJump"
      optional :cont_jump_duration, :message, 4, "PbDuration"
    end
    add_enum "polar_data.PbJumpTest.PbJumpTestType" do
      value :JUMP_TEST_TYPE_SQUAT, 0
      value :JUMP_TEST_TYPE_COUNTER, 1
      value :JUMP_TEST_TYPE_CONTINUOUS, 2
    end
  end
end

module PolarData
  PbJump = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbJump").msgclass
  PbJumpTest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbJumpTest").msgclass
  PbJumpTest::PbJumpTestType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbJumpTest.PbJumpTestType").enummodule
end
