# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_information.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("map_information.proto", :syntax => :proto2) do
    add_message "polar_data.PbMapLocation" do
      required :latitude, :double, 1
      required :longitude, :double, 2
    end
    add_message "polar_data.PbMapInformation" do
      required :centre_point, :message, 1, "polar_data.PbMapLocation"
      optional :data_timestamp, :message, 2, "PbSystemDateTime"
      optional :updated, :bool, 3, default: false
    end
  end
end

module PolarData
  PbMapLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbMapLocation").msgclass
  PbMapInformation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbMapInformation").msgclass
end
