# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nanopb.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nanopb.proto", :syntax => :proto2) do
    add_message "NanoPBOptions" do
      optional :max_size, :int32, 1
      optional :max_count, :int32, 2
    end
  end
end

NanoPBOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NanoPBOptions").msgclass
