# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nightlyrecharge.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("nightlyrecharge.proto", :syntax => :proto2) do
    add_message "polar_data.PbNightlyRecharge" do
      required :time, :message, 1, "PbLocalDateTime"
      required :time2, :message, 2, "PbLocalDateTime"
      required :ans_charge, :float, 3
      required :nightly_recharge_status, :enum, 4, "polar_data.PbNightlyRechargeStatus"
      required :unknown0, :int32, 5
      required :ans_charge_status, :enum, 6, "polar_data.PbNightlyRechargeANSStatus"
      required :beat_to_beat_avg, :int32, 8
      required :heart_rate_variability_avg, :int32, 9
      required :breathing_rate_avg, :uint32, 10
      required :beat_to_beat_ref, :int32, 11
      required :unknown1, :int32, 12
      required :heart_rate_variability_ref, :int32, 13
      required :unknown2, :int32, 14
      required :breathing_rate_ref, :uint32, 15
      required :unknown3, :int32, 16
      required :unknownstr1, :string, 17
      required :unknownstr2, :string, 18
      required :unknownstr3, :string, 19
      required :date, :message, 20, "PbDate"
    end
    add_enum "polar_data.PbNightlyRechargeStatus" do
      value :PB_VERY_POOR, 1
      value :PB_POOR, 2
      value :PB_COMPROMISED, 3
      value :PB_OK, 4
      value :PB_GOOD, 5
      value :PB_VERY_GOOD, 6
    end
    add_enum "polar_data.PbNightlyRechargeANSStatus" do
      value :PB_MUCH_BELOW_USUAL, 1
      value :PB_BELOW_USUAL, 2
      value :PB_USUAL, 3
      value :PB_ABOVE_USUAL, 4
      value :PB_MUCH_ABOVE_USUAL, 5
    end
  end
end

module PolarData
  PbNightlyRecharge = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbNightlyRecharge").msgclass
  PbNightlyRechargeStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbNightlyRechargeStatus").enummodule
  PbNightlyRechargeANSStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbNightlyRechargeANSStatus").enummodule
end
