# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orthostatictestresult.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("orthostatictestresult.proto", :syntax => :proto2) do
    add_message "polar_data.PbOrthostaticTestResult" do
      required :start_time, :message, 1, "PbLocalDateTime"
      required :reset_time, :message, 2, "PbLocalDateTime"
      required :rr_avg_supine, :uint32, 3
      required :rr_long_term_avg_of_supine, :uint32, 4
      required :rr_min_after_standup, :uint32, 5
      required :rr_long_term_avg_of_min_after_standup, :uint32, 6
      required :rr_avg_stand, :uint32, 7
      required :rr_long_term_avg_of_stand, :uint32, 8
    end
  end
end

module PolarData
  PbOrthostaticTestResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbOrthostaticTestResult").msgclass
end
