# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: personalbest.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("personalbest.proto", :syntax => :proto2) do
    add_message "polar_data.PbPersonalBest" do
      optional :distance, :float, 1
      optional :average_speed, :float, 2
      optional :calories, :uint32, 3
      optional :ascent, :float, 4
    end
  end
end

module PolarData
  PbPersonalBest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPersonalBest").msgclass
end
