# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pftp_error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pftp_error.proto", :syntax => :proto2) do
    add_enum "polar_protocol.PbPFtpError" do
      value :OPERATION_SUCCEEDED, 0
      value :REBOOTING, 1
      value :TRY_AGAIN, 2
      value :UNIDENTIFIED_HOST_ERROR, 100
      value :INVALID_COMMAND, 101
      value :INVALID_PARAMETER, 102
      value :NO_SUCH_FILE_OR_DIRECTORY, 103
      value :DIRECTORY_EXISTS, 104
      value :FILE_EXISTS, 105
      value :OPERATION_NOT_PERMITTED, 106
      value :NO_SUCH_USER, 107
      value :TIMEOUT, 108
      value :UNIDENTIFIED_DEVICE_ERROR, 200
      value :NOT_IMPLEMENTED, 201
      value :SYSTEM_BUSY, 202
      value :INVALID_CONTENT, 203
      value :CHECKSUM_FAILURE, 204
      value :DISK_FULL, 205
      value :PREREQUISITE_NOT_MET, 206
      value :INSUFFICIENT_BUFFER, 207
      value :WAIT_FOR_IDLING, 208
    end
  end
end

module PolarProtocol
  PbPFtpError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpError").enummodule
end
