# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pftp_response.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pftp_response.proto", :syntax => :proto2) do
    add_message "polar_protocol.PbPFtpEntry" do
      required :name, :string, 1
      required :size, :uint64, 2
      optional :created, :message, 3, "PbSystemDateTime"
      optional :modified, :message, 4, "PbSystemDateTime"
      optional :touched, :message, 5, "PbSystemDateTime"
    end
    add_message "polar_protocol.PbPFtpDirectory" do
      repeated :entries, :message, 1, "polar_protocol.PbPFtpEntry"
    end
    add_message "polar_protocol.PbPFtpIdentifyDeviceResult" do
      required :device_id, :string, 1
    end
    add_message "polar_protocol.PbPFtpGetSystemTimeResult" do
      required :date, :message, 1, "PbDate"
      required :time, :message, 2, "PbTime"
      required :trusted, :bool, 3
    end
    add_message "polar_protocol.PbPFtpGetLocalTimeResult" do
      required :date, :message, 1, "PbDate"
      required :time, :message, 2, "PbTime"
      optional :tz_offset, :int32, 3
    end
    add_message "polar_protocol.PbPFtpDiskSpaceResult" do
      required :fragment_size, :uint32, 1
      required :total_fragments, :uint64, 2
      required :free_fragments, :uint64, 3
    end
    add_message "polar_protocol.PbPFtpGenerateChallengeTokenResult" do
      required :token, :bytes, 1
    end
    add_message "polar_protocol.PbPFtpBatteryStatusResult" do
      required :battery_status, :uint32, 1
      optional :charging, :bool, 2
    end
    add_message "polar_protocol.PbPFtpGetInactivityPreAlertResult" do
      required :inactivity_pre_alert_on, :bool, 1
    end
  end
end

module PolarProtocol
  PbPFtpEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpEntry").msgclass
  PbPFtpDirectory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpDirectory").msgclass
  PbPFtpIdentifyDeviceResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpIdentifyDeviceResult").msgclass
  PbPFtpGetSystemTimeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpGetSystemTimeResult").msgclass
  PbPFtpGetLocalTimeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpGetLocalTimeResult").msgclass
  PbPFtpDiskSpaceResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpDiskSpaceResult").msgclass
  PbPFtpGenerateChallengeTokenResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpGenerateChallengeTokenResult").msgclass
  PbPFtpBatteryStatusResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpBatteryStatusResult").msgclass
  PbPFtpGetInactivityPreAlertResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpGetInactivityPreAlertResult").msgclass
end
