# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pftp_request.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pftp_request.proto", :syntax => :proto2) do
    add_message "polar_protocol.PbPFtpOperation" do
      required :command, :enum, 1, "polar_protocol.PbPFtpOperation.Command"
      required :path, :string, 2
    end
    add_enum "polar_protocol.PbPFtpOperation.Command" do
      value :GET, 0
      value :PUT, 1
      value :MERGE, 2
      value :REMOVE, 3
    end
    add_message "polar_protocol.PbPFtpSetSystemTimeParams" do
      required :date, :message, 1, "PbDate"
      required :time, :message, 2, "PbTime"
      required :trusted, :bool, 3
    end
    add_message "polar_protocol.PbPFtpSetLocalTimeParams" do
      required :date, :message, 1, "PbDate"
      required :time, :message, 2, "PbTime"
      optional :tz_offset, :int32, 3
    end
    add_message "polar_protocol.PbPFtpGenerateChallengeTokenParams" do
      required :user_id, :uint32, 1
      required :nonse, :bytes, 2
    end
    add_message "polar_protocol.PbPFtpSetAdbModeParams" do
      required :enable, :bool, 1
    end
    add_message "polar_protocol.PbPFtpCleanupDiskSpaceParams" do
      required :required_bytes, :uint64, 1
    end
    add_enum "polar_protocol.PbPFtpQuery" do
      value :IDENTIFY_DEVICE, 0
      value :SET_SYSTEM_TIME, 1
      value :GET_SYSTEM_TIME, 2
      value :SET_LOCAL_TIME, 3
      value :GET_LOCAL_TIME, 4
      value :GET_DISK_SPACE, 5
      value :GENERATE_CHALLENGE_TOKEN, 6
      value :SET_INTERNAL_TEST, 7
      value :GET_BATTERY_STATUS, 8
      value :SET_ADB_MODE, 9
      value :CLEANUP_DISK_SPACE, 10
      value :GET_INACTIVITY_PRE_ALERT, 11
    end
  end
end

module PolarProtocol
  PbPFtpOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpOperation").msgclass
  PbPFtpOperation::Command = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpOperation.Command").enummodule
  PbPFtpSetSystemTimeParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpSetSystemTimeParams").msgclass
  PbPFtpSetLocalTimeParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpSetLocalTimeParams").msgclass
  PbPFtpGenerateChallengeTokenParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpGenerateChallengeTokenParams").msgclass
  PbPFtpSetAdbModeParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpSetAdbModeParams").msgclass
  PbPFtpCleanupDiskSpaceParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpCleanupDiskSpaceParams").msgclass
  PbPFtpQuery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_protocol.PbPFtpQuery").enummodule
end
