# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planned_route.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("planned_route.proto", :syntax => :proto2) do
    add_message "polar_data.PbRoutePoint" do
      required :x_offset, :sint32, 1
      required :y_offset, :sint32, 2
      optional :time_offset, :uint32, 3
      optional :z_offset, :sint32, 4
    end
    add_message "polar_data.PbPlannedRoute" do
      required :route_id, :message, 1, "PbRouteId"
      required :name, :message, 2, "PbOneLineText"
      optional :length, :float, 3
      optional :start_location, :message, 4, "PbLocation"
      optional :start_altitude, :float, 5
      repeated :point, :message, 6, "polar_data.PbRoutePoint"
    end
  end
end

module PolarData
  PbRoutePoint = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbRoutePoint").msgclass
  PbPlannedRoute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPlannedRoute").msgclass
end
