# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poi.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("poi.proto", :syntax => :proto2) do
    add_message "polar_data.PbPointOfInterest" do
      required :location, :message, 1, "PbLocation"
      optional :point_id, :uint64, 2
      optional :name, :message, 3, "PbMultiLineText"
      optional :alarm, :bool, 4
      optional :created, :message, 100, "PbSystemDateTime"
      optional :last_modified, :message, 101, "PbSystemDateTime"
    end
    add_message "polar_data.PbPointOfInterests" do
      repeated :point, :message, 1, "polar_data.PbPointOfInterest"
    end
  end
end

module PolarData
  PbPointOfInterest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPointOfInterest").msgclass
  PbPointOfInterests = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbPointOfInterests").msgclass
end
