# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rr_recordtestresult.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rr_recordtestresult.proto", :syntax => :proto2) do
    add_message "polar_data.PbRRRecordingTestResult" do
      required :start_time, :message, 1, "PbLocalDateTime"
      required :end_time, :message, 2, "PbLocalDateTime"
      required :hr_avg, :uint32, 3
      required :hr_min, :uint32, 4
      required :hr_max, :uint32, 5
    end
  end
end

module PolarData
  PbRRRecordingTestResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbRRRecordingTestResult").msgclass
end
