# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_ace_settings.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile_ace_settings.proto", :syntax => :proto2) do
    add_message "polar_data.PbAceSportProfileSettings" do
      optional :heart_touch, :enum, 1, "polar_data.PbAceSportProfileSettings.PbHeartTouch"
      optional :auto_start, :bool, 4
      optional :stride_sensor_calib_settings, :message, 6, "PbStrideSensorCalibSettings"
    end
    add_enum "polar_data.PbAceSportProfileSettings.PbHeartTouch" do
      value :HEART_TOUCH_OFF, 1
      value :HEART_TOUCH_ACTIVATE_BACKLIGHT, 2
      value :HEART_TOUCH_SHOW_PREVIOUS_LAP, 3
      value :HEART_TOUCH_SHOW_TIME_OF_DAY, 4
    end
  end
end

module PolarData
  PbAceSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAceSportProfileSettings").msgclass
  PbAceSportProfileSettings::PbHeartTouch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAceSportProfileSettings.PbHeartTouch").enummodule
end
