# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_guitar_settings.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile_guitar_settings.proto", :syntax => :proto2) do
    add_message "polar_data.PbGuitarSportProfileSettings" do
      optional :heart_touch, :enum, 1, "polar_data.PbGuitarSportProfileSettings.PbHeartTouch"
      optional :tap_button_action, :enum, 2, "polar_data.PbGuitarSportProfileSettings.PbTapButtonAction"
      optional :vibration, :bool, 3
      optional :auto_start, :bool, 4
      optional :auto_scrolling, :bool, 5
      optional :stride_sensor_calib_settings, :message, 6, "PbStrideSensorCalibSettings"
      optional :sprint_display_activation, :uint32, 7
      optional :sport_tap_button_sensitivity, :enum, 8, "polar_data.PbGuitarSportProfileSettings.PbSportTapButtonSensitivity", default: 3
      optional :swimming_pool, :message, 9, "PbSwimmingPoolInfo"
    end
    add_enum "polar_data.PbGuitarSportProfileSettings.PbHeartTouch" do
      value :HEART_TOUCH_OFF, 1
      value :HEART_TOUCH_ACTIVATE_BACKLIGHT, 2
      value :HEART_TOUCH_SHOW_PREVIOUS_LAP, 3
      value :HEART_TOUCH_SHOW_TIME_OF_DAY, 4
    end
    add_enum "polar_data.PbGuitarSportProfileSettings.PbTapButtonAction" do
      value :TAP_BUTTON_OFF, 1
      value :TAP_BUTTON_TAKE_LAP, 2
      value :TAP_BUTTON_CHANGE_TRAINING_VIEW, 3
      value :TAP_BUTTON_ACTIVATE_BACKLIGHT, 4
    end
    add_enum "polar_data.PbGuitarSportProfileSettings.PbSportTapButtonSensitivity" do
      value :SPORT_TAP_BUTTON_SENSITIVITY_OFF, 1
      value :SPORT_TAP_BUTTON_SENSITIVITY_VERY_LOW, 5
      value :SPORT_TAP_BUTTON_SENSITIVITY_LOW, 2
      value :SPORT_TAP_BUTTON_SENSITIVITY_MEDIUM, 3
      value :SPORT_TAP_BUTTON_SENSITIVITY_HIGH, 4
    end
  end
end

module PolarData
  PbGuitarSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbGuitarSportProfileSettings").msgclass
  PbGuitarSportProfileSettings::PbHeartTouch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbGuitarSportProfileSettings.PbHeartTouch").enummodule
  PbGuitarSportProfileSettings::PbTapButtonAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbGuitarSportProfileSettings.PbTapButtonAction").enummodule
  PbGuitarSportProfileSettings::PbSportTapButtonSensitivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbGuitarSportProfileSettings.PbSportTapButtonSensitivity").enummodule
end
