# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
require 'sportprofile_guitar_settings_pb'
require 'sportprofile_mclaren_settings_pb'
require 'sportprofile_ace_settings_pb'
require 'sportprofile_avalon_settings_pb'
require 'sportprofile_archer_settings_pb'
require 'sportprofile_astra_settings_pb'
require 'sportprofile_maserati_settings_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile.proto", :syntax => :proto2) do
    add_message "polar_data.PbSirius2TrainingDisplay" do
      repeated :item, :enum, 1, "polar_data.PbTrainingDisplayItem"
    end
    add_message "polar_data.PbSirius2DisplaySettings" do
      repeated :display, :message, 1, "polar_data.PbSirius2TrainingDisplay"
      optional :last_shown_display, :uint32, 2
      optional :added_default_displays, :uint32, 3
    end
    add_message "polar_data.PbAutoLapSettings" do
      required :automatic_lap, :enum, 1, "polar_data.PbAutoLapSettings.PbAutomaticLap"
      optional :automatic_lap_distance, :float, 2
      optional :automatic_lap_duration, :message, 3, "PbDuration"
    end
    add_enum "polar_data.PbAutoLapSettings.PbAutomaticLap" do
      value :AUTOMATIC_LAP_OFF, 1
      value :AUTOMATIC_LAP_DISTANCE, 2
      value :AUTOMATIC_LAP_DURATION, 3
      value :AUTOMATIC_LAP_LOCATION, 4
    end
    add_message "polar_data.PbTrainingReminder" do
      required :reminder_type, :enum, 1, "polar_data.PbTrainingReminder.PbTrainingReminderType"
      optional :reminder_text, :message, 2, "PbOneLineText"
      optional :calorie_reminder_value, :uint32, 3
      optional :time_reminder_value, :message, 4, "PbDuration"
      optional :distance_reminder_value, :float, 5
    end
    add_enum "polar_data.PbTrainingReminder.PbTrainingReminderType" do
      value :TRAINING_REMINDER_OFF, 1
      value :TRAINING_REMINDER_CALORIES_BASED, 2
      value :TRAINING_REMINDER_DISTANCE_BASED, 3
      value :TRAINING_REMINDER_TIME_BASED, 4
    end
    add_message "polar_data.PbSportProfileSettings" do
      optional :volume, :message, 1, "PbVolume"
      optional :speed_view, :enum, 2, "polar_data.PbSportProfileSettings.PbSpeedView"
      optional :zone_optimizer_setting, :enum, 3, "polar_data.PbSportProfileSettings.PbZoneOptimizerSetting"
      optional :heart_rate_view, :enum, 4, "PbHeartRateView"
      optional :sensor_broadcasting_hr, :bool, 5
      optional :zone_limits, :message, 6, "PbZones"
      optional :training_reminder, :message, 7, "polar_data.PbTrainingReminder"
      optional :voice_guidance, :bool, 8
      optional :gps_setting, :enum, 9, "polar_data.PbSportProfileSettings.PbGPSSetting"
      optional :autolap_settings, :message, 10, "polar_data.PbAutoLapSettings"
      optional :altitude_setting, :enum, 11, "polar_data.PbSportProfileSettings.PbAltitudeSetting"
      optional :power_view, :enum, 12, "polar_data.PbSportProfileSettings.PbPowerView"
      optional :stride_speed_source, :enum, 13, "polar_data.PbSportProfileSettings.PbStrideSpeedSource", default: 1
      repeated :remote_button_actions, :enum, 14, "polar_data.PbSportProfileSettings.PbRemoteButtonAction"
      optional :hr_zone_lock_available, :bool, 15
      optional :speed_zone_lock_available, :bool, 16
      optional :power_zone_lock_available, :bool, 17
      optional :swimming_units, :enum, 18, "polar_data.PbSportProfileSettings.PbSwimmingUnits"
    end
    add_enum "polar_data.PbSportProfileSettings.PbSpeedView" do
      value :SPEED_VIEW_PACE, 1
      value :SPEED_VIEW_SPEED, 2
    end
    add_enum "polar_data.PbSportProfileSettings.PbZoneOptimizerSetting" do
      value :ZONEOPTIMIZER_OFF, 1
      value :ZONEOPTIMIZER_MODIFIED_OFF, 2
      value :ZONEOPTIMIZER_DEFAULT, 3
      value :ZONEOPTIMIZER_MODIFIED, 4
    end
    add_enum "polar_data.PbSportProfileSettings.PbGPSSetting" do
      value :GPS_OFF, 0
      value :GPS_ON_NORMAL, 1
      value :GPS_ON_LONG, 2
    end
    add_enum "polar_data.PbSportProfileSettings.PbAltitudeSetting" do
      value :ALTITUDE_OFF, 0
      value :ALTITUDE_ON, 1
    end
    add_enum "polar_data.PbSportProfileSettings.PbPowerView" do
      value :POWER_VIEW_WATT, 1
      value :POWER_VIEW_WATT_PER_KG, 2
      value :POWER_VIEW_FTP_PERCENT, 3
    end
    add_enum "polar_data.PbSportProfileSettings.PbStrideSpeedSource" do
      value :STRIDE_SPEED_SOURCE_STRIDE, 1
      value :STRIDE_SPEED_SOURCE_GPS, 2
    end
    add_enum "polar_data.PbSportProfileSettings.PbRemoteButtonAction" do
      value :REMOTE_BUTTON_RING_BELL, 1
      value :REMOTE_BUTTON_ACTIVATE_BACKLIGHT, 2
      value :REMOTE_BUTTON_CHANGE_TRAINING_VIEW, 3
      value :REMOTE_BUTTON_TAKE_LAP, 4
      value :REMOTE_BUTTON_ACTIVATE_SAFETY_LIGHT, 5
    end
    add_enum "polar_data.PbSportProfileSettings.PbSwimmingUnits" do
      value :SWIMMING_METERS, 0
      value :SWIMMING_YARDS, 1
    end
    add_message "polar_data.PbAutoPause" do
      required :trigger, :enum, 1, "polar_data.PbAutoPause.PbAutoPauseTrigger"
      optional :speed_threshold, :float, 2
    end
    add_enum "polar_data.PbAutoPause.PbAutoPauseTrigger" do
      value :AUTO_PAUSE_OFF, 0
      value :AUTO_PAUSE_TRIGGER_SPEED, 1
    end
    add_message "polar_data.PbSportProfile" do
      optional :identifier, :uint64, 1
      required :sport_identifier, :message, 2, "PbSportIdentifier"
      optional :settings, :message, 3, "polar_data.PbSportProfileSettings"
      optional :sirius2_display_settings, :message, 4, "polar_data.PbSirius2DisplaySettings"
      optional :sport_factor, :float, 5
      optional :aerobic_threshold, :uint32, 6
      optional :anaerobic_threshold, :uint32, 7
      required :last_modified, :message, 8, "PbSystemDateTime"
      optional :sprint_threshold, :float, 9
      optional :auto_pause, :message, 10, "polar_data.PbAutoPause"
      optional :guitar_settings, :message, 200, "polar_data.PbGuitarSportProfileSettings"
      optional :mclaren_settings, :message, 201, "polar_data.PbMcLarenSportProfileSettings"
      optional :ace_settings, :message, 202, "polar_data.PbAceSportProfileSettings"
      optional :avalon_settings, :message, 203, "polar_data.PbAvalonSportProfileSettings"
      optional :archer_settings, :message, 204, "polar_data.PbArcherSportProfileSettings"
      optional :astra_settings, :message, 205, "polar_data.PbAstraSportProfileSettings"
      optional :maserati_settings, :message, 206, "polar_data.PbMaseratiSportProfileSettings"
    end
    add_enum "polar_data.PbTrainingDisplayItem" do
      value :TIME_OF_DAY, 2
      value :STOPWATCH, 3
      value :CURRENT_LAP_TIME, 6
      value :LAST_LAP_TIME, 7
      value :LAST_AUTOMATIC_LAP_TIME, 8
      value :ALTITUDE, 10
      value :ASCENT, 11
      value :DESCENT, 12
      value :INCLINOMETER, 13
      value :TEMPERATURE, 15
      value :CURRENT_LAP_ASCENT, 16
      value :CURRENT_LAP_DESCENT, 17
      value :CURRENT_LAP_VAM, 18
      value :CURRENT_HEART_RATE, 20
      value :AVERAGE_HEART_RATE, 21
      value :MAXIMUM_HEART_RATE, 22
      value :CURRENT_LAP_AVERAGE_HEART_RATE, 24
      value :CURRENT_LAP_MAX_HEART_RATE, 25
      value :PREVIOUS_LAP_AVERAGE_HEART_RATE, 26
      value :PREVIOUS_LAP_MAX_HEART_RATE, 28
      value :CALORIES, 27
      value :ZONE_POINTER, 32
      value :TIME_IN_ZONE, 33
      value :RR_VARIATION, 35
      value :DISTANCE, 37
      value :CURRENT_LAP_DISTANCE, 38
      value :PREVIOUS_LAP_DISTANCE, 39
      value :SPEED_OR_PACE, 41
      value :SPEED_OR_PACE_AVERAGE, 42
      value :SPEED_OR_PACE_MAXIMUM, 43
      value :CURRENT_LAP_SPEED_OR_PACE, 44
      value :SPEED_ZONE_POINTER, 45
      value :TIME_IN_SPEED_ZONE, 46
      value :CURRENT_LAP_MAX_PACE_OR_SPEED, 47
      value :PREVIOUS_LAP_MAX_PACE_OR_SPEED, 48
      value :PREVIOUS_LAP_SPEED_OR_PACE, 220
      value :VERTICAL_SPEED_MOVING_AVERAGE, 221
      value :CADENCE, 49
      value :AVERAGE_CADENCE, 50
      value :MAXIMUM_CADENCE, 240
      value :CURRENT_LAP_CADENCE, 51
      value :CURRENT_LAP_MAX_CADENCE, 52
      value :PREVIOUS_LAP_CADENCE, 53
      value :STRIDE_LENGTH, 54
      value :AVERAGE_STRIDE_LENGTH, 55
      value :CURRENT_POWER, 56
      value :CURRENT_POWER_LEFT_RIGHT_BALANCE, 57
      value :MAXIMUM_FORCE, 58
      value :POWER_ZONE_POINTER, 59
      value :AVERAGE_POWER, 60
      value :MAXIMUM_POWER, 61
      value :AVERAGE_POWER_LEFT_RIGHT_BALANCE, 62
      value :CURRENT_LAP_AVERAGE_POWER, 63
      value :CURRENT_LAP_MAXIMUM_POWER, 64
      value :CURRENT_LAP_AVERAGE_POWER_LR_BALANCE, 65
      value :TIME_IN_POWER_ZONE, 66
      value :PREVIOUS_LAP_AVERAGE_POWER, 67
      value :PREVIOUS_LAP_MAXIMUM_POWER, 68
      value :PREVIOUS_LAP_AVERAGE_POWER_LR_BALANCE, 230
      value :REST_TIME, 69
      value :POOL_COUNTER, 70
      value :MULTISPORT_DURATION, 88
      value :MULTISPORT_DISTANCE, 89
      value :MULTISPORT_CALORIES, 90
      value :MULTISPORT_ASCENT, 91
      value :MULTISPORT_DESCENT, 92
      value :HEART_RATE_ZONES, 100
      value :MULTISPORT_HEART_RATE_ZONES, 101
      value :LOCATION_GUIDE, 102
      value :POWER_ZONES, 103
      value :FORCE_GRAPH, 104
      value :TIME_BASED_SPEED_ZONES, 105
      value :CURRENT_ALAP_AVERAGE_HEART_RATE, 200
      value :CURRENT_ALAP_TIME, 201
      value :CURRENT_ALAP_AVERAGE_POWER, 202
      value :CURRENT_ALAP_MAXIMUM_POWER, 203
      value :CURRENT_ALAP_SPEED_OR_PACE, 204
      value :CURRENT_ALAP_DISTANCE, 205
      value :CURRENT_ALAP_ASCENT, 206
      value :CURRENT_ALAP_DESCENT, 207
      value :CURRENT_ALAP_CADENCE, 208
      value :CURRENT_ALAP_AVERAGE_POWER_LR_BALANCE, 209
      value :CURRENT_ALAP_MAX_HEART_RATE, 210
      value :CURRENT_ALAP_MAX_SPEED, 211
      value :CURRENT_ALAP_MAX_CADENCE, 212
    end
  end
end

module PolarData
  PbSirius2TrainingDisplay = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSirius2TrainingDisplay").msgclass
  PbSirius2DisplaySettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSirius2DisplaySettings").msgclass
  PbAutoLapSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAutoLapSettings").msgclass
  PbAutoLapSettings::PbAutomaticLap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAutoLapSettings.PbAutomaticLap").enummodule
  PbTrainingReminder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTrainingReminder").msgclass
  PbTrainingReminder::PbTrainingReminderType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTrainingReminder.PbTrainingReminderType").enummodule
  PbSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings").msgclass
  PbSportProfileSettings::PbSpeedView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbSpeedView").enummodule
  PbSportProfileSettings::PbZoneOptimizerSetting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbZoneOptimizerSetting").enummodule
  PbSportProfileSettings::PbGPSSetting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbGPSSetting").enummodule
  PbSportProfileSettings::PbAltitudeSetting = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbAltitudeSetting").enummodule
  PbSportProfileSettings::PbPowerView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbPowerView").enummodule
  PbSportProfileSettings::PbStrideSpeedSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbStrideSpeedSource").enummodule
  PbSportProfileSettings::PbRemoteButtonAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbRemoteButtonAction").enummodule
  PbSportProfileSettings::PbSwimmingUnits = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfileSettings.PbSwimmingUnits").enummodule
  PbAutoPause = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAutoPause").msgclass
  PbAutoPause::PbAutoPauseTrigger = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAutoPause.PbAutoPauseTrigger").enummodule
  PbSportProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportProfile").msgclass
  PbTrainingDisplayItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTrainingDisplayItem").enummodule
end
