# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_maserati_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile_maserati_settings.proto", :syntax => :proto2) do
    add_message "polar_data.PbMaseratiSportProfileSettings" do
      optional :heart_touch, :enum, 1, "polar_data.PbMaseratiSportProfileSettings.PbHeartTouch"
      optional :tap_button_action, :enum, 2, "polar_data.PbMaseratiSportProfileSettings.PbTapButtonAction"
      optional :vibration, :bool, 3
      optional :auto_start, :bool, 4
    end
    add_enum "polar_data.PbMaseratiSportProfileSettings.PbHeartTouch" do
      value :HEART_TOUCH_OFF, 1
      value :HEART_TOUCH_ACTIVATE_BACKLIGHT, 2
      value :HEART_TOUCH_SHOW_PREVIOUS_LAP, 3
      value :HEART_TOUCH_SHOW_TIME_OF_DAY, 4
    end
    add_enum "polar_data.PbMaseratiSportProfileSettings.PbTapButtonAction" do
      value :TAP_BUTTON_OFF, 1
      value :TAP_BUTTON_TAKE_LAP, 2
      value :TAP_BUTTON_CHANGE_TRAINING_VIEW, 3
      value :TAP_BUTTON_ACTIVATE_BACKLIGHT, 4
    end
  end
end

module PolarData
  PbMaseratiSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbMaseratiSportProfileSettings").msgclass
  PbMaseratiSportProfileSettings::PbHeartTouch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbMaseratiSportProfileSettings.PbHeartTouch").enummodule
  PbMaseratiSportProfileSettings::PbTapButtonAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbMaseratiSportProfileSettings.PbTapButtonAction").enummodule
end
