# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_avalon_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile_avalon_settings.proto", :syntax => :proto2) do
    add_message "polar_data.PbAvalonSportProfileSettings" do
      optional :heart_touch, :enum, 1, "polar_data.PbAvalonSportProfileSettings.PbHeartTouch"
      optional :vibration, :bool, 3
      optional :auto_start, :bool, 4
    end
    add_enum "polar_data.PbAvalonSportProfileSettings.PbHeartTouch" do
      value :HEART_TOUCH_OFF, 1
      value :HEART_TOUCH_ACTIVATE_BACKLIGHT, 2
      value :HEART_TOUCH_SHOW_PREVIOUS_LAP, 3
      value :HEART_TOUCH_SHOW_TIME_OF_DAY, 4
    end
  end
end

module PolarData
  PbAvalonSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAvalonSportProfileSettings").msgclass
  PbAvalonSportProfileSettings::PbHeartTouch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAvalonSportProfileSettings.PbHeartTouch").enummodule
end
