# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sport.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sport.proto", :syntax => :proto2) do
    add_message "polar_data.PbSportTranslation" do
      required :id, :message, 1, "PbLanguageId"
      required :text, :message, 2, "PbOneLineText"
    end
    add_message "polar_data.PbSport" do
      required :identifier, :message, 1, "PbSportIdentifier"
      required :parent_identifier, :message, 2, "PbSportIdentifier"
      repeated :translation, :message, 3, "polar_data.PbSportTranslation"
      optional :factor, :float, 4
      repeated :stages, :message, 5, "PbSportIdentifier"
      optional :sport_type, :enum, 6, "polar_data.PbSport.PbSportType", default: 1
      optional :speed_zones_enabled, :bool, 7, default: false
      optional :created, :message, 100, "PbSystemDateTime"
      optional :last_modified, :message, 101, "PbSystemDateTime"
    end
    add_enum "polar_data.PbSport.PbSportType" do
      value :SPORT_TYPE_SINGLE_SPORT, 1
      value :SPORT_TYPE_MULTI_SPORT, 2
      value :SPORT_TYPE_SUB_SPORT, 3
      value :SPORT_TYPE_FREE_MULTI_SPORT, 4
    end
  end
end

module PolarData
  PbSportTranslation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSportTranslation").msgclass
  PbSport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSport").msgclass
  PbSport::PbSportType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSport.PbSportType").enummodule
end
