# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_astra_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile_astra_settings.proto", :syntax => :proto2) do
    add_message "polar_data.PbAstraSportProfileSettings" do
      optional :vibration, :bool, 3
    end
  end
end

module PolarData
  PbAstraSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbAstraSportProfileSettings").msgclass
end
