# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sportprofile_mclaren_settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("sportprofile_mclaren_settings.proto", :syntax => :proto2) do
    add_message "polar_data.PbMcLarenSportProfileSettings" do
      required :auto_start, :bool, 4
    end
  end
end

module PolarData
  PbMcLarenSportProfileSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbMcLarenSportProfileSettings").msgclass
end
