# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structures.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("structures.proto", :syntax => :proto2) do
    add_message "PbVolumeTarget" do
      required :target_type, :enum, 1, "PbVolumeTarget.PbVolymeTargetType"
      optional :duration, :message, 2, "PbDuration"
      optional :distance, :float, 3
      optional :calories, :uint32, 4
    end
    add_enum "PbVolumeTarget.PbVolymeTargetType" do
      value :VOLUME_TARGET_TYPE_DURATION, 0
      value :VOLUME_TARGET_TYPE_DISTANCE, 1
      value :VOLUME_TARGET_TYPE_CALORIES, 2
    end
    add_message "PbTrainingLoad" do
      optional :training_load_val, :uint32, 1
      optional :recovery_time, :message, 2, "PbDuration"
      optional :carbohydrate_consumption, :uint32, 3
      optional :protein_consumption, :uint32, 4
      optional :fat_consumption, :uint32, 5
    end
    add_message "PbHeartRateZone" do
      required :lower_limit, :uint32, 1
      required :higher_limit, :uint32, 2
    end
    add_message "PbSpeedZone" do
      required :lower_limit, :float, 1
      required :higher_limit, :float, 2
    end
    add_message "PbPowerZone" do
      required :lower_limit, :uint32, 1
      required :higher_limit, :uint32, 2
    end
    add_message "PbZones" do
      repeated :heart_rate_zone, :message, 1, "PbHeartRateZone"
      repeated :speed_zone, :message, 2, "PbSpeedZone"
      repeated :power_zone, :message, 3, "PbPowerZone"
      optional :heart_rate_setting_source, :enum, 10, "PbHeartRateZoneSettingSource"
      optional :power_setting_source, :enum, 11, "PbPowerZoneSettingSource"
      optional :speed_setting_source, :enum, 12, "PbSpeedZoneSettingSource"
    end
    add_message "PbBleMac" do
      required :mac, :bytes, 1
      required :type, :enum, 2, "PbMacType"
    end
    add_message "PbBleDeviceName" do
      required :name, :string, 1
    end
    add_message "PbDeviceId" do
      required :device_id, :string, 1
    end
    add_message "PbRunningIndex" do
      required :value, :uint32, 1
      optional :calculation_time, :message, 2, "PbDuration"
    end
    add_message "PbSportIdentifier" do
      required :value, :uint64, 1
    end
    add_message "PbOneLineText" do
      required :text, :string, 1
    end
    add_message "PbMultiLineText" do
      required :text, :string, 1
    end
    add_message "PbLanguageId" do
      required :language, :string, 1
    end
    add_message "PbTrainingSessionTargetId" do
      required :value, :uint64, 1
      optional :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_message "PbTrainingSessionFavoriteId" do
      required :value, :uint64, 1
      optional :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_message "PbRouteId" do
      required :value, :uint64, 1
    end
    add_message "PbSwimmingPoolInfo" do
      optional :pool_length, :float, 1
      required :swimming_pool_type, :enum, 2, "PbSwimmingPoolUnits"
    end
    add_message "PbTrainingProgramId" do
      required :value, :uint64, 1
    end
    add_message "PbEventId" do
      required :value, :uint64, 1
    end
    add_message "PbPauseTime" do
      required :start, :message, 1, "PbDuration"
      required :duration, :message, 2, "PbDuration"
    end
  end
end

PbVolumeTarget = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbVolumeTarget").msgclass
PbVolumeTarget::PbVolymeTargetType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbVolumeTarget.PbVolymeTargetType").enummodule
PbTrainingLoad = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTrainingLoad").msgclass
PbHeartRateZone = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbHeartRateZone").msgclass
PbSpeedZone = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSpeedZone").msgclass
PbPowerZone = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbPowerZone").msgclass
PbZones = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbZones").msgclass
PbBleMac = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbBleMac").msgclass
PbBleDeviceName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbBleDeviceName").msgclass
PbDeviceId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbDeviceId").msgclass
PbRunningIndex = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbRunningIndex").msgclass
PbSportIdentifier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSportIdentifier").msgclass
PbOneLineText = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbOneLineText").msgclass
PbMultiLineText = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbMultiLineText").msgclass
PbLanguageId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbLanguageId").msgclass
PbTrainingSessionTargetId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTrainingSessionTargetId").msgclass
PbTrainingSessionFavoriteId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTrainingSessionFavoriteId").msgclass
PbRouteId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbRouteId").msgclass
PbSwimmingPoolInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSwimmingPoolInfo").msgclass
PbTrainingProgramId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTrainingProgramId").msgclass
PbEventId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbEventId").msgclass
PbPauseTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbPauseTime").msgclass
