#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'types.pb'; rescue LoadError; end

module PolarData
  # forward declarations
  class PbSwimmingStyleChange < ::ProtocolBuffers::Message; end
  class PbSwimmingPoolMetric < ::ProtocolBuffers::Message; end
  class PbSwimmingSamples < ::ProtocolBuffers::Message; end

  class PbSwimmingStyleChange < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbSwimmingStyleChange"

    required ::PbSwimmingStyle, :style, 1
    required ::PbDuration, :timestamp, 2
  end

  class PbSwimmingPoolMetric < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbSwimmingPoolMetric"

    required ::PbDuration, :start_offset, 1
    required ::PbDuration, :duration, 2
    optional ::PbSwimmingStyle, :style, 3
    optional :uint32, :strokes, 4
  end

  class PbSwimmingSamples < ::ProtocolBuffers::Message
    set_fully_qualified_name "polar_data.PbSwimmingSamples"

    required ::PbLocalDateTime, :start, 1
    repeated ::PolarData::PbSwimmingPoolMetric, :pool_metric, 3
  end

end
