# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncinfo.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("syncinfo.proto", :syntax => :proto2) do
    add_message "polar_data.PbSyncInfo" do
      required :last_modified, :message, 1, "PbSystemDateTime"
      repeated :changed_path, :string, 2
      optional :last_synchronized, :message, 3, "PbSystemDateTime"
      optional :full_sync_required, :bool, 4, default: true
    end
  end
end

module PolarData
  PbSyncInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSyncInfo").msgclass
end
