# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team_member.proto

require 'google/protobuf'

require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("team_member.proto", :syntax => :proto2) do
    add_message "polar_data.PbTeamMember" do
      required :team_identifier, :uint64, 1
      optional :player_number, :uint32, 2
      optional :player_role, :message, 3, "PbOneLineText"
    end
  end
end

module PolarData
  PbTeamMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTeamMember").msgclass
end
