# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_session_target.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
require 'exercise_phases_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("training_session_target.proto", :syntax => :proto2) do
    add_message "polar_data.PbSteadyRacePace" do
      required :duration, :message, 1, "PbDuration"
      required :distance, :float, 2
    end
    add_message "polar_data.PbExerciseTarget" do
      required :target_type, :enum, 1, "PbExerciseTargetType"
      optional :sport_id, :message, 2, "PbSportIdentifier"
      optional :volume_target, :message, 3, "PbVolumeTarget"
      optional :phases, :message, 4, "polar_data.PbPhases"
      optional :route, :message, 5, "PbRouteId"
      optional :steady_race_pace, :message, 6, "polar_data.PbSteadyRacePace"
    end
    add_message "polar_data.PbTrainingSessionTarget" do
      required :name, :message, 2, "PbOneLineText"
      optional :sport_id, :message, 3, "PbSportIdentifier"
      optional :start_time, :message, 4, "PbLocalDateTime"
      optional :description, :message, 5, "PbMultiLineText"
      repeated :exercise_target, :message, 6, "polar_data.PbExerciseTarget"
      optional :target_done, :bool, 7
      optional :duration, :message, 8, "PbDuration"
      optional :training_program_id, :message, 9, "PbTrainingProgramId"
      optional :event_id, :message, 10, "PbEventId"
    end
  end
end

module PolarData
  PbSteadyRacePace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSteadyRacePace").msgclass
  PbExerciseTarget = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbExerciseTarget").msgclass
  PbTrainingSessionTarget = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTrainingSessionTarget").msgclass
end
