# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("types.proto", :syntax => :proto2) do
    add_message "PbRangeOptions" do
      optional :min_value, :int32, 1
      optional :max_value, :int32, 2
    end
    add_message "PbDate" do
      required :year, :uint32, 1
      required :month, :uint32, 2
      required :day, :uint32, 3
    end
    add_message "PbTime" do
      required :hour, :uint32, 1
      required :minute, :uint32, 2
      required :seconds, :uint32, 3
      optional :millis, :uint32, 4, default: 0
    end
    add_message "PbSystemDateTime" do
      required :date, :message, 1, "PbDate"
      required :time, :message, 2, "PbTime"
      required :trusted, :bool, 3
    end
    add_message "PbLocalDateTime" do
      required :date, :message, 1, "PbDate"
      required :time, :message, 2, "PbTime"
      required :OBSOLETE_trusted, :bool, 3
      optional :time_zone_offset, :int32, 4
    end
    add_message "PbDuration" do
      optional :hours, :uint32, 1, default: 0
      optional :minutes, :uint32, 2, default: 0
      optional :seconds, :uint32, 3, default: 0
      optional :millis, :uint32, 4, default: 0
    end
    add_message "PbLocation" do
      required :latitude, :double, 1
      required :longitude, :double, 2
      optional :timestamp, :message, 3, "PbSystemDateTime"
      optional :fix, :enum, 4, "PbLocation.Fix", default: 0
      optional :satellites, :uint32, 5, default: 0
    end
    add_enum "PbLocation.Fix" do
      value :FIX_NONE, 0
      value :FIX_2D, 1
      value :FIX_3D, 2
    end
    add_message "PbSensorOffline" do
      required :start_index, :uint32, 1
      required :stop_index, :uint32, 2
    end
    add_message "PbVolume" do
      required :volume, :uint32, 1
    end
    add_message "PbStrideSensorCalibSettings" do
      required :running_factor, :float, 1
      required :calib_type, :enum, 2, "PbStrideSensorCalibSettings.PbStrideCalibType"
      optional :running_factor_source, :enum, 3, "PbStrideSensorCalibSettings.PbRunningFactorSource", default: 0
    end
    add_enum "PbStrideSensorCalibSettings.PbStrideCalibType" do
      value :STRIDE_CALIB_MANUAL, 0
      value :STRIDE_CALIB_AUTO, 1
    end
    add_enum "PbStrideSensorCalibSettings.PbRunningFactorSource" do
      value :RUNNING_FACTOR_SOURCE_DEFAULT, 0
      value :RUNNING_FACTOR_SOURCE_AUTO_CALIBRATION, 1
      value :RUNNING_FACTOR_SOURCE_MANUAL_CALIBRATION, 2
    end
    add_enum "PbDataType" do
      value :UNDEFINED, 0
      value :INHERITED, 1
      value :ENUM, 2
      value :MILLIS, 3
      value :SECOND, 4
      value :MINUTE, 5
      value :HOUR, 6
      value :HOURS, 7
      value :DAY, 8
      value :MONTH, 9
      value :YEAR, 10
      value :WEIGHT, 11
      value :HEIGHT, 12
      value :VO2MAX, 13
      value :HEARTRATE, 20
      value :HR_PERCENT, 21
      value :HR_RESERVE, 22
      value :SPEED, 23
      value :CADENCE, 24
      value :ALTITUDE, 25
      value :POWER, 26
      value :POWER_LRB, 27
      value :POWER_PI, 28
      value :TEMPERATURE, 29
      value :ACTIVITY, 30
      value :STRIDE_LENGTH, 31
      value :INCLINE, 32
      value :DECLINE, 33
      value :DISTANCE, 52
      value :ENERGY, 53
      value :FAT_PERCENTS, 54
      value :ASCENT, 55
      value :DESCENT, 56
      value :LATITUDE, 57
      value :LONGITUDE, 58
      value :HERTZ, 59
      value :PERCENT, 60
      value :CUMULATED_ACTIVITY_DAY, 61
      value :RUNNING_INDEX, 62
      value :RR_INTERVAL, 63
      value :Z_INDEX, 64
      value :EXERCISE_TARGET_INDEX, 65
      value :TIME_ZONE_OFFSET, 66
      value :WHEEL_SIZE, 67
      value :FITNESS_CLASS, 68
      value :ACCELERATION, 69
      value :CRANK_LENGTH, 70
      value :ANGLE_DEGREE, 71
      value :NEWTON, 72
      value :FUNCTIONAL_THRESHOLD_POWER, 73
      value :CALORIES, 74
      value :SPEED_CALIBRATION_OFFSET, 75
    end
    add_enum "PbHeartRateView" do
      value :HEART_RATE_VIEW_BPM, 1
      value :HEART_RATE_VIEW_PERCENTS_OF_HR_RESERVE, 2
      value :HEART_RATE_VIEW_PERCENTS_OF_MAX_HR, 3
    end
    add_enum "PbUnitSystem" do
      value :METRIC, 1
      value :IMPERIAL, 2
    end
    add_enum "PbTimeSelection" do
      value :TIME_1, 1
      value :TIME_2, 2
    end
    add_enum "PbTimeFormat" do
      value :TIME_FORMAT_24H, 1
      value :TIME_FORMAT_12H, 2
    end
    add_enum "PbTimeFormatSeparator" do
      value :TIME_FORMAT_SEPARATOR_DOT, 1
      value :TIME_FORMAT_SEPARATOR_COLON, 2
    end
    add_enum "PbStartDayOfWeek" do
      value :MONDAY, 1
      value :SATURDAY, 2
      value :SUNDAY, 3
    end
    add_enum "PbDateFormatSeparator" do
      value :DOT, 1
      value :SLASH, 2
      value :HYPHEN, 3
    end
    add_enum "PbDateFormat" do
      value :DD_MM_YYYY, 1
      value :MM_DD_YYYY, 2
      value :YYYY_MM_DD, 3
    end
    add_enum "PbFeatureType" do
      value :FEATURE_TYPE_HEART_RATE, 1
      value :FEATURE_TYPE_RR_INTERVAL, 2
      value :FEATURE_TYPE_SPEED, 3
      value :FEATURE_TYPE_DISTANCE, 4
      value :FEATURE_TYPE_BIKE_CADENCE, 5
      value :FEATURE_TYPE_BIKE_POWER, 6
      value :FEATURE_TYPE_GPS_LOCATION, 7
      value :FEATURE_TYPE_RUNNING_CADENCE, 8
      value :FEATURE_TYPE_PRESS_TEMPERATURE, 9
      value :FEATURE_TYPE_ALTITUDE, 10
      value :FEATURE_TYPE_STEPS, 11
      value :FEATURE_TYPE_ACTIVITY, 12
      value :FEATURE_TYPE_STRIDE_LENGTH, 13
      value :FEATURE_TYPE_RSC_MOVING_TYPE, 14
      value :FEATURE_TYPE_JUMP_HEIGTH, 15
      value :FEATURE_TYPE_COMPASS_HEADING, 16
      value :FEATURE_TYPE_GPS_SPEED, 17
      value :FEATURE_TYPE_GPS_DISTANCE, 18
      value :FEATURE_TYPE_GPS_ALTITUDE, 19
      value :FEATURE_TYPE_BIKE_WHEEL_REVOLUTION, 20
      value :FEATURE_TYPE_BIKE_CRANK_REVOLUTION, 21
      value :FEATURE_TYPE_AS_SPEED, 22
      value :FEATURE_TYPE_AS_CADENCE, 23
      value :FEATURE_TYPE_AS_DISTANCE, 24
      value :FEATURE_TYPE_AS_SWR_STATE, 25
      value :FEATURE_TYPE_BATTERY_LEVEL, 26
      value :FEATURE_TYPE_FILE_TRANSFER, 27
      value :FEATURE_TYPE_PUSH_NOTIFICATIONS, 28
      value :FEATURE_TYPE_WEIGHT_SCALE, 29
    end
    add_enum "PbMovingType" do
      value :WALKING, 0
      value :RUNNING, 1
      value :STANDING, 2
    end
    add_enum "PbOperationType" do
      value :MULTIPLY, 1
      value :SUM, 2
    end
    add_enum "PbExerciseFeedback" do
      value :FEEDBACK_NONE, 1
      value :FEEDBACK_1, 2
      value :FEEDBACK_2, 3
      value :FEEDBACK_3, 4
      value :FEEDBACK_4, 5
      value :FEEDBACK_5, 6
      value :FEEDBACK_6, 7
      value :FEEDBACK_7, 8
      value :FEEDBACK_8, 9
      value :FEEDBACK_9, 10
      value :FEEDBACK_10, 11
      value :FEEDBACK_11, 12
      value :FEEDBACK_12, 13
      value :FEEDBACK_13, 14
      value :FEEDBACK_14, 15
      value :FEEDBACK_15, 16
      value :FEEDBACK_16, 17
      value :FEEDBACK_17, 18
    end
    add_enum "PbHeartRateZoneSettingSource" do
      value :HEART_RATE_ZONE_SETTING_SOURCE_DEFAULT, 0
      value :HEART_RATE_ZONE_SETTING_SOURCE_THRESHOLD, 1
      value :HEART_RATE_ZONE_SETTING_SOURCE_FREE, 2
    end
    add_enum "PbPowerZoneSettingSource" do
      value :POWER_ZONE_SETTING_SOURCE_DEFAULT, 0
      value :POWER_ZONE_SETTING_SOURCE_FREE, 1
    end
    add_enum "PbSpeedZoneSettingSource" do
      value :SPEED_ZONE_SETTING_SOURCE_DEFAULT, 0
      value :SPEED_ZONE_SETTING_SOURCE_FREE, 1
    end
    add_enum "PbMacType" do
      value :MAC_TYPE_PUBLIC, 0
      value :MAC_TYPE_STATIC, 1
      value :MAC_TYPE_PRIVATE_NONRESOLVABLE, 2
      value :MAC_TYPE_PRIVATE_RESOLVABLE, 3
      value :MAC_TYPE_BT_CLASSIC, 4
    end
    add_enum "PbSwimmingStyle" do
      value :OTHER, -1
      value :TURN, 0
      value :OTHER_SWIMMING, 10
      value :FREESTYLE, 11
      value :BREASTSTROKE, 12
      value :BACKSTROKE, 13
      value :BUTTERFLY, 14
    end
    add_enum "PbSwimmingPoolUnits" do
      value :SWIMMING_POOL_METERS, 0
      value :SWIMMING_POOL_YARDS, 1
    end
    add_enum "PbExerciseTargetType" do
      value :EXERCISE_TARGET_TYPE_FREE, 0
      value :EXERCISE_TARGET_TYPE_VOLUME, 1
      value :EXERCISE_TARGET_TYPE_PHASED, 2
      value :EXERCISE_TARGET_TYPE_ROUTE, 3
      value :EXERCISE_TARGET_TYPE_STEADY_RACE_PACE, 4
      value :EXERCISE_TARGET_TYPE_ROUTE_RACE_PACE, 5
    end
  end
end

PbRangeOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbRangeOptions").msgclass
PbDate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbDate").msgclass
PbTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTime").msgclass
PbSystemDateTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSystemDateTime").msgclass
PbLocalDateTime = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbLocalDateTime").msgclass
PbDuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbDuration").msgclass
PbLocation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbLocation").msgclass
PbLocation::Fix = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbLocation.Fix").enummodule
PbSensorOffline = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSensorOffline").msgclass
PbVolume = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbVolume").msgclass
PbStrideSensorCalibSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbStrideSensorCalibSettings").msgclass
PbStrideSensorCalibSettings::PbStrideCalibType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbStrideSensorCalibSettings.PbStrideCalibType").enummodule
PbStrideSensorCalibSettings::PbRunningFactorSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbStrideSensorCalibSettings.PbRunningFactorSource").enummodule
PbDataType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbDataType").enummodule
PbHeartRateView = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbHeartRateView").enummodule
PbUnitSystem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbUnitSystem").enummodule
PbTimeSelection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTimeSelection").enummodule
PbTimeFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTimeFormat").enummodule
PbTimeFormatSeparator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbTimeFormatSeparator").enummodule
PbStartDayOfWeek = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbStartDayOfWeek").enummodule
PbDateFormatSeparator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbDateFormatSeparator").enummodule
PbDateFormat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbDateFormat").enummodule
PbFeatureType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbFeatureType").enummodule
PbMovingType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbMovingType").enummodule
PbOperationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbOperationType").enummodule
PbExerciseFeedback = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbExerciseFeedback").enummodule
PbHeartRateZoneSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbHeartRateZoneSettingSource").enummodule
PbPowerZoneSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbPowerZoneSettingSource").enummodule
PbSpeedZoneSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSpeedZoneSettingSource").enummodule
PbMacType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbMacType").enummodule
PbSwimmingStyle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSwimmingStyle").enummodule
PbSwimmingPoolUnits = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbSwimmingPoolUnits").enummodule
PbExerciseTargetType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PbExerciseTargetType").enummodule
