# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_database.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_database.proto", :syntax => :proto2) do
    add_message "polar_data.PbUserDb" do
      required :current_user_index, :uint32, 1
    end
  end
end

module PolarData
  PbUserDb = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDb").msgclass
end
