# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_physdata.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_physdata.proto", :syntax => :proto2) do
    add_message "polar_data.PbUserBirthday" do
      required :value, :message, 1, "PbDate"
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_message "polar_data.PbUserGender" do
      required :value, :enum, 1, "polar_data.PbUserGender.Gender"
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_enum "polar_data.PbUserGender.Gender" do
      value :MALE, 1
      value :FEMALE, 2
    end
    add_message "polar_data.PbUserHrAttribute" do
      required :value, :uint32, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
      optional :setting_source, :enum, 3, "polar_data.PbUserHrAttribute.HrSettingSource"
    end
    add_enum "polar_data.PbUserHrAttribute.HrSettingSource" do
      value :SOURCE_DEFAULT, 0
      value :SOURCE_AGE_BASED, 1
      value :SOURCE_USER, 2
      value :SOURCE_MEASURED, 3
      value :SOURCE_KEEP, 4
    end
    add_message "polar_data.PbUserWeight" do
      required :value, :float, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
      optional :setting_source, :enum, 3, "polar_data.PbUserWeight.WeightSettingSource"
    end
    add_enum "polar_data.PbUserWeight.WeightSettingSource" do
      value :SOURCE_DEFAULT, 0
      value :SOURCE_USER, 2
      value :SOURCE_MEASURED, 3
    end
    add_message "polar_data.PbUserHeight" do
      required :value, :float, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_message "polar_data.PbUserVo2Max" do
      required :value, :uint32, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
      optional :setting_source, :enum, 3, "polar_data.PbUserVo2Max.Vo2MaxSettingSource"
    end
    add_enum "polar_data.PbUserVo2Max.Vo2MaxSettingSource" do
      value :SOURCE_DEFAULT, 0
      value :SOURCE_ESTIMATE, 1
      value :SOURCE_USER, 2
      value :SOURCE_FITNESSTEST, 3
    end
    add_message "polar_data.PbUserTrainingBackground" do
      required :value, :enum, 1, "polar_data.PbUserTrainingBackground.TrainingBackground"
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_enum "polar_data.PbUserTrainingBackground.TrainingBackground" do
      value :OCCASIONAL, 10
      value :REGULAR, 20
      value :FREQUENT, 30
      value :HEAVY, 40
      value :SEMI_PRO, 50
      value :PRO, 60
    end
    add_message "polar_data.PbUserTypicalDay" do
      required :value, :enum, 1, "polar_data.PbUserTypicalDay.TypicalDay"
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_enum "polar_data.PbUserTypicalDay.TypicalDay" do
      value :MOSTLY_SITTING, 1
      value :MOSTLY_STANDING, 2
      value :MOSTLY_MOVING, 3
    end
    add_message "polar_data.PbWeeklyRecoveryTimeSum" do
      required :value, :float, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_message "polar_data.PbSpeedCalibrationOffset" do
      required :value, :float, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
    end
    add_message "polar_data.PbUserFunctionalThresholdPower" do
      required :value, :uint32, 1
      required :last_modified, :message, 2, "PbSystemDateTime"
      optional :setting_source, :enum, 3, "polar_data.PbUserFunctionalThresholdPower.FTPSettingSource"
    end
    add_enum "polar_data.PbUserFunctionalThresholdPower.FTPSettingSource" do
      value :SOURCE_DEFAULT, 0
      value :SOURCE_ESTIMATE, 1
      value :SOURCE_USER, 2
    end
    add_message "polar_data.PbUserPhysData" do
      required :birthday, :message, 1, "polar_data.PbUserBirthday"
      required :gender, :message, 2, "polar_data.PbUserGender"
      optional :weight, :message, 3, "polar_data.PbUserWeight"
      optional :height, :message, 4, "polar_data.PbUserHeight"
      optional :maximum_heartrate, :message, 5, "polar_data.PbUserHrAttribute"
      optional :resting_heartrate, :message, 6, "polar_data.PbUserHrAttribute"
      optional :OBSOLETE_sitting_heartrate, :message, 7, "polar_data.PbUserHrAttribute"
      optional :aerobic_threshold, :message, 8, "polar_data.PbUserHrAttribute"
      optional :anaerobic_threshold, :message, 9, "polar_data.PbUserHrAttribute"
      optional :vo2max, :message, 10, "polar_data.PbUserVo2Max"
      optional :training_background, :message, 11, "polar_data.PbUserTrainingBackground"
      optional :typical_day, :message, 12, "polar_data.PbUserTypicalDay"
      optional :weekly_recovery_time_sum, :message, 13, "polar_data.PbWeeklyRecoveryTimeSum"
      optional :speed_calibration_offset, :message, 14, "polar_data.PbSpeedCalibrationOffset"
      optional :functional_threshold_power, :message, 15, "polar_data.PbUserFunctionalThresholdPower"
      optional :last_modified, :message, 100, "PbSystemDateTime"
      optional :snapshot_start_time, :message, 101, "PbLocalDateTime"
    end
  end
end

module PolarData
  PbUserBirthday = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserBirthday").msgclass
  PbUserGender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserGender").msgclass
  PbUserGender::Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserGender.Gender").enummodule
  PbUserHrAttribute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserHrAttribute").msgclass
  PbUserHrAttribute::HrSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserHrAttribute.HrSettingSource").enummodule
  PbUserWeight = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserWeight").msgclass
  PbUserWeight::WeightSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserWeight.WeightSettingSource").enummodule
  PbUserHeight = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserHeight").msgclass
  PbUserVo2Max = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserVo2Max").msgclass
  PbUserVo2Max::Vo2MaxSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserVo2Max.Vo2MaxSettingSource").enummodule
  PbUserTrainingBackground = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserTrainingBackground").msgclass
  PbUserTrainingBackground::TrainingBackground = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserTrainingBackground.TrainingBackground").enummodule
  PbUserTypicalDay = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserTypicalDay").msgclass
  PbUserTypicalDay::TypicalDay = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserTypicalDay.TypicalDay").enummodule
  PbWeeklyRecoveryTimeSum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbWeeklyRecoveryTimeSum").msgclass
  PbSpeedCalibrationOffset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbSpeedCalibrationOffset").msgclass
  PbUserFunctionalThresholdPower = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserFunctionalThresholdPower").msgclass
  PbUserFunctionalThresholdPower::FTPSettingSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserFunctionalThresholdPower.FTPSettingSource").enummodule
  PbUserPhysData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserPhysData").msgclass
end
