# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_prefs.proto

require 'google/protobuf'

require 'types_pb'
require 'structures_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_prefs.proto", :syntax => :proto2) do
    add_message "polar_data.PbLocalizationPreferences" do
      optional :language, :message, 1, "PbLanguageId"
      optional :unit_system, :enum, 2, "PbUnitSystem"
      optional :time_format, :enum, 3, "PbTimeFormat"
      optional :time_format_separator, :enum, 4, "PbTimeFormatSeparator"
      optional :date_format, :enum, 5, "PbDateFormat"
      optional :date_format_separator, :enum, 6, "PbDateFormatSeparator"
      optional :firstday_of_week, :enum, 7, "PbStartDayOfWeek"
    end
    add_message "polar_data.PbTrainingPreferences" do
      optional :OBSOLETE_heart_rate_zone_lock, :uint32, 1
      optional :heart_rate_view, :enum, 2, "PbHeartRateView"
    end
    add_message "polar_data.PbActivityGoalPreferences" do
      required :visible, :bool, 1
    end
    add_message "polar_data.PbGeneralPreferences" do
      optional :localization_preferences, :message, 1, "polar_data.PbLocalizationPreferences"
      optional :training_preferences, :message, 2, "polar_data.PbTrainingPreferences"
      optional :activity_goal_preferences, :message, 3, "polar_data.PbActivityGoalPreferences"
      required :last_modified, :message, 101, "PbSystemDateTime"
    end
  end
end

module PolarData
  PbLocalizationPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbLocalizationPreferences").msgclass
  PbTrainingPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbTrainingPreferences").msgclass
  PbActivityGoalPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbActivityGoalPreferences").msgclass
  PbGeneralPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbGeneralPreferences").msgclass
end
