# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_devset.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_devset.proto", :syntax => :proto2) do
    add_message "polar_data.PbUserDeviceGeneralSettings" do
      optional :OBSOLETE_time_selection, :enum, 1, "PbTimeSelection"
      optional :OBSOLETE_time2_offset, :int32, 2
      optional :watch_face, :enum, 3, "polar_data.PbUserDeviceGeneralSettings.PbWatchFace"
      optional :button_lock_mode, :enum, 4, "polar_data.PbUserDeviceGeneralSettings.PbButtonLockMode"
      optional :button_sound_volume, :message, 5, "PbVolume"
      optional :vibration_mode, :bool, 7
      optional :handedness, :enum, 8, "polar_data.PbUserDeviceGeneralSettings.PbHandedness"
      optional :exeview_inverted, :bool, 9
      optional :tap_button_sensitivity, :enum, 10, "polar_data.PbUserDeviceGeneralSettings.PbTapButtonSensitivity"
      optional :inactivity_alert, :enum, 11, "polar_data.PbUserDeviceGeneralSettings.PbInactivityAlert"
      optional :ble_connect_mode_enable, :bool, 12
    end
    add_enum "polar_data.PbUserDeviceGeneralSettings.PbWatchFace" do
      value :BASIC, 1
      value :AWARD, 2
      value :USER_NAME, 3
      value :EVENT, 4
      value :ANALOG, 5
      value :BIG, 6
      value :ACTIVITY, 7
    end
    add_enum "polar_data.PbUserDeviceGeneralSettings.PbButtonLockMode" do
      value :MANUAL, 1
      value :AUTO, 2
    end
    add_enum "polar_data.PbUserDeviceGeneralSettings.PbHandedness" do
      value :WU_IN_LEFT_HAND, 1
      value :WU_IN_RIGHT_HAND, 2
    end
    add_enum "polar_data.PbUserDeviceGeneralSettings.PbTapButtonSensitivity" do
      value :TAP_BUTTON_SENSITIVITY_OFF, 1
      value :TAP_BUTTON_SENSITIVITY_VERY_LOW, 5
      value :TAP_BUTTON_SENSITIVITY_LOW, 2
      value :TAP_BUTTON_SENSITIVITY_MEDIUM, 3
      value :TAP_BUTTON_SENSITIVITY_HIGH, 4
    end
    add_enum "polar_data.PbUserDeviceGeneralSettings.PbInactivityAlert" do
      value :INACTIVITY_ALERT_OFF, 1
      value :INACTIVITY_ALERT_ON, 2
    end
    add_message "polar_data.PbUserDeviceAlarmSettings" do
      required :alarm_mode, :enum, 1, "polar_data.PbUserDeviceAlarmSettings.PbAlarmMode"
      required :alarm_time, :message, 2, "PbTime"
    end
    add_enum "polar_data.PbUserDeviceAlarmSettings.PbAlarmMode" do
      value :ALARM_MODE_OFF, 1
      value :ALARM_MODE_ONCE, 2
      value :ALARM_MODE_MON_TO_FRI, 3
      value :ALARM_MODE_EVERY_DAY, 4
    end
    add_message "polar_data.PbUserDeviceCountdownSettings" do
      required :countdown_time, :message, 1, "PbDuration"
    end
    add_message "polar_data.PbUserDeviceJumpTestSettings" do
      required :cont_jump_duration, :message, 1, "PbDuration"
    end
    add_message "polar_data.PbIntervalTimerValue" do
      required :interval_timer_type, :enum, 1, "polar_data.PbIntervalTimerValue.PbIntervalTimerType"
      optional :interval_timer_duration, :message, 2, "PbDuration"
      optional :interval_timer_distance, :float, 3
    end
    add_enum "polar_data.PbIntervalTimerValue.PbIntervalTimerType" do
      value :INTERVAL_TIMER_TYPE_DURATION, 1
      value :INTERVAL_TIMER_TYPE_DISTANCE, 2
    end
    add_message "polar_data.PbUserIntervalTimerSettings" do
      repeated :interval_timer_value, :message, 1, "polar_data.PbIntervalTimerValue"
    end
    add_message "polar_data.PbUserEndTimeEstimatorSettings" do
      optional :end_time_estimator_target, :float, 1
    end
    add_message "polar_data.PbUserDeviceResearchSettings" do
      optional :accelerometer_raw_data_enable, :bool, 1
      optional :gyroscope_raw_data_enable, :bool, 2
      optional :magnetometer_raw_data_enable, :bool, 3
      optional :linear_acceleration_data_enable, :bool, 4
    end
    add_message "polar_data.PbUserSafetyLightSettings" do
      required :mode, :enum, 1, "polar_data.PbUserSafetyLightSettings.PbSafetyLightMode"
      optional :activation_level, :enum, 2, "polar_data.PbUserSafetyLightSettings.PbSafetyLightActivationLevel"
      optional :blink_rate, :enum, 3, "polar_data.PbUserSafetyLightSettings.PbSafetyLightBlinkRate"
    end
    add_enum "polar_data.PbUserSafetyLightSettings.PbSafetyLightMode" do
      value :SAFETY_LIGHT_MANUAL, 1
      value :SAFETY_LIGHT_AUTOMATIC, 2
    end
    add_enum "polar_data.PbUserSafetyLightSettings.PbSafetyLightActivationLevel" do
      value :ACTIVATION_LEVEL_DARK, 1
      value :ACTIVATION_LEVEL_DUSK, 2
      value :ACTIVATION_LEVEL_LIGHT, 3
    end
    add_enum "polar_data.PbUserSafetyLightSettings.PbSafetyLightBlinkRate" do
      value :BLINK_RATE_OFF, 1
      value :BLINK_RATE_SLOW, 2
      value :BLINK_RATE_FAST, 3
      value :BLINK_RATE_VERY_FAST, 4
    end
    add_message "polar_data.PbDoNotDisturbSettings" do
      required :enabled, :bool, 1
      optional :start, :message, 2, "PbTime"
      optional :end, :message, 3, "PbTime"
    end
    add_message "polar_data.PbUserSmartWatchNotificationSettings" do
      required :enabled, :bool, 1
      optional :preview_enabled, :bool, 2
      optional :do_not_disturb_settings, :message, 3, "polar_data.PbDoNotDisturbSettings"
      optional :sounds_enabled, :bool, 4
    end
    add_message "polar_data.PbUserDeviceSettings" do
      required :general_settings, :message, 1, "polar_data.PbUserDeviceGeneralSettings"
      optional :alarm_settings, :message, 2, "polar_data.PbUserDeviceAlarmSettings"
      optional :countdown_settings, :message, 3, "polar_data.PbUserDeviceCountdownSettings"
      optional :jumptest_settings, :message, 4, "polar_data.PbUserDeviceJumpTestSettings"
      optional :interval_timer_settings, :message, 5, "polar_data.PbUserIntervalTimerSettings"
      optional :end_time_estimator_settings, :message, 6, "polar_data.PbUserEndTimeEstimatorSettings"
      optional :research_settings, :message, 7, "polar_data.PbUserDeviceResearchSettings"
      optional :safety_light_settings, :message, 8, "polar_data.PbUserSafetyLightSettings"
      optional :smart_watch_notification_settings, :message, 9, "polar_data.PbUserSmartWatchNotificationSettings"
      required :last_modified, :message, 101, "PbSystemDateTime"
    end
  end
end

module PolarData
  PbUserDeviceGeneralSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceGeneralSettings").msgclass
  PbUserDeviceGeneralSettings::PbWatchFace = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceGeneralSettings.PbWatchFace").enummodule
  PbUserDeviceGeneralSettings::PbButtonLockMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceGeneralSettings.PbButtonLockMode").enummodule
  PbUserDeviceGeneralSettings::PbHandedness = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceGeneralSettings.PbHandedness").enummodule
  PbUserDeviceGeneralSettings::PbTapButtonSensitivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceGeneralSettings.PbTapButtonSensitivity").enummodule
  PbUserDeviceGeneralSettings::PbInactivityAlert = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceGeneralSettings.PbInactivityAlert").enummodule
  PbUserDeviceAlarmSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceAlarmSettings").msgclass
  PbUserDeviceAlarmSettings::PbAlarmMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceAlarmSettings.PbAlarmMode").enummodule
  PbUserDeviceCountdownSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceCountdownSettings").msgclass
  PbUserDeviceJumpTestSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceJumpTestSettings").msgclass
  PbIntervalTimerValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbIntervalTimerValue").msgclass
  PbIntervalTimerValue::PbIntervalTimerType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbIntervalTimerValue.PbIntervalTimerType").enummodule
  PbUserIntervalTimerSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserIntervalTimerSettings").msgclass
  PbUserEndTimeEstimatorSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserEndTimeEstimatorSettings").msgclass
  PbUserDeviceResearchSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceResearchSettings").msgclass
  PbUserSafetyLightSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserSafetyLightSettings").msgclass
  PbUserSafetyLightSettings::PbSafetyLightMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserSafetyLightSettings.PbSafetyLightMode").enummodule
  PbUserSafetyLightSettings::PbSafetyLightActivationLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserSafetyLightSettings.PbSafetyLightActivationLevel").enummodule
  PbUserSafetyLightSettings::PbSafetyLightBlinkRate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserSafetyLightSettings.PbSafetyLightBlinkRate").enummodule
  PbDoNotDisturbSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbDoNotDisturbSettings").msgclass
  PbUserSmartWatchNotificationSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserSmartWatchNotificationSettings").msgclass
  PbUserDeviceSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserDeviceSettings").msgclass
end
