# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_test_prefs.proto

require 'google/protobuf'

require 'types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_test_prefs.proto", :syntax => :proto2) do
    add_message "polar_data.PbUserTestPreferences" do
      optional :orthostatic_test_reset, :message, 1, "PbLocalDateTime"
      required :last_modified, :message, 101, "PbSystemDateTime"
    end
  end
end

module PolarData
  PbUserTestPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("polar_data.PbUserTestPreferences").msgclass
end
